- ros_topic_name: "/model/tethys/joint/vertical_fins_joint/cmd_pos"
  gz_topic_name: "/model/tethys/joint/vertical_fins_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  lazy: true
  direction: BIDIRECTIONAL
- ros_topic_name: "/model/tethys/joint/propeller_joint/cmd_vel"
  gz_topic_name: "/model/tethys/joint/propeller_joint/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  lazy: true
  direction: BIDIRECTIONAL
- ros_topic_name: "/model/tethys/joint/horizontal_fins_joint/cmd_pos"
  gz_topic_name: "/model/tethys/joint/horizontal_fins_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  lazy: true
- ros_topic_name: "/tethys/navsat"
  gz_topic_name: "/tethys/navsat"
  ros_type_name: "sensor_msgs/msg/NavSatFix"
  gz_type_name: "gz.msgs.NavSat"
  lazy: true
  direction: GZ_TO_ROS
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  lazy: true
  direction: BIDIRECTIONAL
